name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  check-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Hämta koden
        uses: actions/checkout@v4

      - name: Installera Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Installera dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Kör lint
        working-directory: ./frontend
        run: npm run lint

      - name: Bygg frontend
        working-directory: ./frontend
        run: npm run build
